---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-8.5
    run_list:
    - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[gitweb::default]
    attributes:
      gitweb:
        hostname: gitweb.vagrant
